# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

CampaignChain\Hook\TimespanBundle\Entity\Timespan:
    properties:
        date:
            - Type: \DateTime